server:
  port: 8080
  servlet:
    context-path: /mgs

#百度语音转文字请求api 管理
baidu:
  appid: wx822cffe6132b893e
  apikey: v1Xlqs19A89Vnx2zx1hoosVU
  secretkey: mMti3EKfU8GeOHwmpAMadmwqM5n3mi11

# admin username and password
admin:
  admin-name: root
  admin-password: zhanghang120

#腾讯地图
tencent:
  key: JDBBZ-7S6R3-I7K32-37QZA-5PIX2-WMBUB #腾讯地图密钥

#微信相关
wx:
  appid: wx822cffe6132b893e
  secret: df2af9fe6ab23c283443ec7390026573
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/garbagesort?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    username: root  # 配置数据库用户
    password: 123456  # 配置数据库密码
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  # 日期返回格式
  jackson:
    date-format: yy/MM/dd

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: top.miyamoto.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 文件路径管理
upload:
  image:
    path: /var/project/image
  #    path: /var/project/image    # linux or mac
  #    path: E:/testpath/image/                 # windows
  record:
    path: /var/project/record
  #    path: /var/project/record   # linux or mac
  #    path: E:/testpath/record/   # windows
  excel:
    path: E:/testpath/excel/
#    path: E:/testpath/excel/